//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudEDUServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE_CANCEL
    {
        public int ID { get; set; }
        public decimal PRICE { get; set; }
        public Nullable<int> RATE { get; set; }
        public string TITLE { get; set; }
        public string INTRO { get; set; }
        public Nullable<int> TEACHER { get; set; }
        public Nullable<int> CATEGORY { get; set; }
        public string COURSE_STATUS { get; set; }
    }
}
