//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudEDUServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CloudEDUEntities : DbContext
    {
        public CloudEDUEntities()
            : base("name=CloudEDUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CATEGORY> CATEGORies { get; set; }
        public DbSet<COMMENT> COMMENTs { get; set; }
        public DbSet<COURSE> COURSEs { get; set; }
        public DbSet<DOCUMENT> DOCUMENTs { get; set; }
        public DbSet<LESSON> LESSONs { get; set; }
        public DbSet<PARENT_GUIDE> PARENT_GUIDE { get; set; }
        public DbSet<RECOMMENDATION> RECOMMENDATIONs { get; set; }
        public DbSet<RES_TYPE> RES_TYPE { get; set; }
        public DbSet<RESOURCE> RESOURCEs { get; set; }
        public DbSet<ATTEND> ATTENDs { get; set; }
        public DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public DbSet<NOTE> NOTEs { get; set; }
        public DbSet<OPR_LOG> OPR_LOG { get; set; }
        public DbSet<MANAGER> MANAGERs { get; set; }
        public DbSet<PERMISSION> PERMISSIONs { get; set; }
        public DbSet<TYPE> TYPEs { get; set; }
        public DbSet<SALEORDER> SALEORDERs { get; set; }
        public DbSet<COURSE_CANCEL> COURSE_CANCEL { get; set; }
        public DbSet<Course_OK> Course_OK { get; set; }
        public DbSet<COURSE_PENDING> COURSE_PENDING { get; set; }
    }
}
