//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudEDUServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISSION
    {
        public PERMISSION()
        {
            this.MANAGERs = new HashSet<MANAGER>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string TYPE { get; set; }
    
        public virtual ICollection<MANAGER> MANAGERs { get; set; }
    }
}
