//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudEDUServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESOURCE
    {
        public int ID { get; set; }
        public int LESSON_ID { get; set; }
        public string TITLE { get; set; }
        public string INTRO { get; set; }
        public int TYPE { get; set; }
        public string URL { get; set; }
    
        public virtual LESSON LESSON { get; set; }
        public virtual RES_TYPE RES_TYPE { get; set; }
    }
}
